server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: pandora
  datasource:
    url: jdbc:postgresql://localhost:5432/pandora
    username: postgres
    password: postgres

ldap:
  url: https://sigenu.cujae.edu.cu/sigenu-ldap-cujae/ldap
  username: disertic.ldap
  password: disertic*2022*ldap
