server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: pandora
  datasource:
    url: jdbc:postgresql://localhost:5432/pandora
    username: postgres
    password: postgres

ldap:
  url: ${PROD_LDAP_URL}
  username: ${PROD_LDAP_USERNAME}
  password: ${PROD_LDAP_PASSWORD}
