server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: pandora
  datasource:
    url: jdbc:postgresql://localhost:5432/pandora
    username: postgres
    password: postgres

ldap:
  url: https://url.to.cujae/ldap
  username: ldap-username
  password: ldap-password
